default: &default
  adapter: postgresql
  encoding: unicode
  username: damian
  database: tmp_app
  pool: 5

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  #password:
  #host: localhost
